spring:
  profiles:
    default: prod
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: postgres

  test:
    database:
      replace: none
  sql:
    init:
      platform: postgres

server:
  port: 8003