version: "3.5"

services:
  config-service:
    container_name: config-service
    build: config-service/
    image: config-service
    ports:
      - "8888:8888"

  discovery-service:
    container_name: discovery-service
    build: discovery-service/
    image: discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    restart: always

  product-service:
    container_name: product-service
    build: product-service/
    image: product-service
    ports:
      - "8001:8001"
    depends_on:
      - product-database
      - discovery-service
      - config-service
    restart: on-failure

  product-database:
    container_name: product-database
    image: postgres:15.2-alpine
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./product-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - product_database:/var/lib/postgresql/data
    restart: always

  user-service:
    container_name: user-service
    build: user-service/
    image: user-service
    ports:
      - "8002:8002"
    depends_on:
      - user-database
      - discovery-service
      - config-service
    restart: on-failure

  user-database:
    container_name: user-database
    image: postgres:15.2-alpine
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user_database:/var/lib/postgresql/data
    restart: always

  order-service:
    container_name: order-service
    build: order-service/
    image: order-service
    ports:
      - "8003:8003"
    depends_on:
      - order-database
      - discovery-service
      - config-service
    restart: on-failure

  order-database:
    container_name: order-database
    image: postgres:15.2-alpine
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - order_database:/var/lib/postgresql/data
    restart: always

  python-service:
    container_name: python-service
    build: python-service/
    ports:
      - "8004:8004"
    restart: always

volumes:
  product_database:
  user_database:
  order_database: